import unittest

from classes.autogenerated import Application


class TestCase(unittest.TestCase):
    def __init__(self, *arg, **kwargs):
        super(TestCase, self).__init__(*arg, **kwargs)
        base_url = 'api.2gis.ru/2.0'
        self.app = Application(base_url)

    @classmethod
    def setUpClass(cls):
        pass

    @classmethod
    def tearDownClass(cls):
        pass
